// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:0fd729ad-3434-45bd-b837-8f10861fc3d7',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'penguinhub-hosting-mobilehub-1448774034',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1ydo1j11812o9.cloudfront.net',
    'aws_mobile_analytics_app_id': '7b18865c21424d53a54994bd35667d34',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '05e019c9-98ec-4213-bcba-feef9cea18b6',
    'aws_project_name': 'Penguin_Hub1',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'penguinhub-mobilehub-1448774034',
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "PenguinWorkBot",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
